"""empty message

Revision ID: 93d5e5c72824
Revises: ef26a8c2f9e8
Create Date: 2024-09-01 17:39:49.864590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d5e5c72824'
down_revision: Union[str, None] = 'ef26a8c2f9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_payment_details_id'), 'payment_details', ['id'])
    op.create_unique_constraint(op.f('uq_shopping_sessions_id'), 'shopping_sessions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_shopping_sessions_id'), 'shopping_sessions', type_='unique')
    op.drop_constraint(op.f('uq_payment_details_id'), 'payment_details', type_='unique')
    # ### end Alembic commands ###
