"""empty message

Revision ID: 055076746c2b
Revises: 
Create Date: 2024-08-13 16:58:28.480787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055076746c2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), server_default='05a608ab-34a0-42d6-b352-1710ab47bda8', nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_per_unit', sa.Double(), nullable=False),
    sa.Column('price_with_discount', sa.Double(), sa.Computed('price_per_unit - (price_per_unit * (discount*0.01))', ), nullable=False),
    sa.Column('number_in_stock', sa.BIGINT(), nullable=False),
    sa.Column('rating', sa.Double(), nullable=True),
    sa.Column('discount', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'isbn', name=op.f('pk_books')),
    sa.UniqueConstraint('id', name=op.f('uq_books_id')),
    sa.UniqueConstraint('isbn', name=op.f('uq_books_isbn'))
    )
    op.create_table('categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name='uq_categories_name'),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), server_default='user', nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('authors',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_authors_book_id_books'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors'))
    )
    op.create_table('book_category_assoc',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_category_assoc_book_id_books')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_book_category_assoc_category_id_categories')),
    sa.PrimaryKeyConstraint('book_id', 'category_id', name=op.f('pk_book_category_assoc'))
    )
    op.create_table('images',
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_images_book_id_books')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_table('orders',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('order_status', sa.String(), server_default='pending', nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_sum', sa.Double(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('publishers',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_publishers_book_id_books'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishers'))
    )
    op.create_table('shopping_sessions',
    sa.Column('id', sa.UUID(), server_default='af9fece6-85db-4636-ad16-2f69f66915f4', nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total', sa.Double(), server_default='0', nullable=True),
    sa.Column('expiration_time', sa.DateTime(timezone=True), server_default='2024-08-14 16:58:28.287820', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_sessions')),
    sa.UniqueConstraint('id', name=op.f('uq_shopping_sessions_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_shopping_sessions_user_id'))
    )
    op.create_index('ix_shopping_sessions', 'shopping_sessions', ['expiration_time'], unique=False)
    op.create_table('book_order_assoc',
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('count_ordered', sa.BIGINT(), server_default='1', nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_order_assoc_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_book_order_assoc_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_order_assoc')),
    sa.UniqueConstraint('order_id', 'book_id', name='uq_book_order_assoc_order_id_book_id')
    )
    op.create_table('cart_items',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_cart_items_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['shopping_sessions.id'], name=op.f('fk_cart_items_session_id_shopping_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'book_id', 'id', name=op.f('pk_cart_items'))
    )
    op.create_table('payment_details',
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('payment_provider', sa.String(), nullable=True),
    sa.Column('amount', sa.Double(), server_default='0.0', nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_details_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_details')),
    sa.UniqueConstraint('order_id', name=op.f('uq_payment_details_order_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_details')
    op.drop_table('cart_items')
    op.drop_table('book_order_assoc')
    op.drop_index('ix_shopping_sessions', table_name='shopping_sessions')
    op.drop_table('shopping_sessions')
    op.drop_table('publishers')
    op.drop_table('orders')
    op.drop_table('images')
    op.drop_table('book_category_assoc')
    op.drop_table('authors')
    op.drop_table('users')
    op.drop_table('categories')
    op.drop_table('books')
    # ### end Alembic commands ###
